{{- if eq (.Values.global.oauth.type | default "") "HTPasswd" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.oauth.secretName }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
    - secretKey: htpasswd
      remoteRef:
        key: {{ default "secret/data/hub/htpasswd" .Values.htpasswdKeyPath }}
        property: content
  target:
    name: {{ .Values.global.oauth.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        htpasswd: |-
          {{ "{{ .htpasswd }}" }}
{{- end }}
